[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "gunicorn src.nfl_data.main:app -k uvicorn.workers.UvicornWorker -w 4 --bind 0.0.0.0:${PORT:-8080} --forwarded-allow-ips='*'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.metadata]
cpu = "250m"
memory = "1Gi"

[deploy.variables]
REDIS_URL = "${REDIS_URL}" 