[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "gunicorn src.nfl_data.main:app -k uvicorn.workers.UvicornWorker -w 4 --bind 0.0.0.0:$PORT"
healthcheckPath = "/api"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.metadata]
cpu = "250m"
memory = "512Mi" 